FROM node:20-alpine AS builder
WORKDIR /app
#ENV VITE_API_BASE_URL=/api
ENV NEXT_PUBLIC_API_BASE_URL=/api
COPY package.json package-lock.json* ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3002
CMD ["nginx", "-g", "daemon off;"]
